# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kernville Cowork
email: justin@kernvillecowork.com
description: >- # this means to ignore newlines until "baseurl:"
  Kernville Cowork's vision is to: * Create a community for collaboration,
  innovation, and continuous learning * Create a pathway for local students to
  become interested and get involved with careers in technology that they can
  utilize while staying in the valley * Create a destination for skilled
  distributed workers that have a desire to live and work in a small thriving
  community with access to outdoor adventure.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://kernvillecowork.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kernvillecowork
# github_username:  jekyll

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-archives

# minimal-mistakes specific configs
permalink: /:categories/:title/
breadcrumbs: true
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      share: true
      # sidebar:
      #   nav: "posts"
      read_time: true
      author_profile: true
      comments: true
      related: true
minimal_mistakes_skin: "dirt"
title_separator: "|"
teaser: /assets/images/KernvilleCowork_wwyp_0.2_300h.png
logo: /assets/images/KernvilleCowork_wwyp_0.2_300h.png
og_image: /assets/images/KernvilleCowork_wwyp_0.2_300h.png
search: true
twitter:
  username: kernvillecowork
social:
  type:  Organization # Person or Organization (defaults to Person)
  #name:  # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/KernvilleCowork"
    - "https://www.facebook.com/workfromkernville"
    - "https://www.instagram.com/kernvillecowork"
    - "https://www.linkedin.com/company/kernville-cowork/"
author:
  name     : "Justin Powers"
  avatar   : "/assets/images/justin_headshot.jpg"
  bio      : "Justin is the founder of Kernville Cowork."
  location : "Kernville, CA"
timezone: "America/Los_Angeles"

# jekyll-archives specific configs
jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    category: '/:name/'

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
